- name: Playbook1 - データ生成と保存
  hosts: localhost
  tasks: 
    - name: データを生成1 fact
      set_fact:
        my_var1: "data from playbook1 set_fact, register"

    - name: データを表示
      debug:
        msg: "{{ my_var1 }}"

    - name: factsから表示
      debug:
        msg: "{{ ansible_stats.my_var1 }}"
