- name: Playbook1 - データ生成と保存
  hosts: localhost
  tasks: 
    - name: データを生成
      set_fact:
        my_var1: "Data from my_var1"

    - name: 値を保存
      set_stats:
        data: 
          my_var1: "{{ my_var1 }}"

    - name: 値を表示
      debug:
        msg: "{{ ansible_stats.my_var1 }}"
      
    
