---
- name: expose test
  hosts: localhost
  tasks:
    - name: expose
      command: cat /opt/new.txt
      register: file_content

    - name: Print file content
      debug:
        var: file_content.stdout
      
