---
- name: expose test
  hosts: localhost
  connection: local
  tasks:
    - name: List contents of /opt
      shell: ls -l /opt
      register: dir_contents

    - name: Print directory contents
      debug:
        var: dir_contents.stdout
