---
- name: expose test
  hosts: localhost
  connection: local
  tasks:
    - name: expose
      shell: cat /opt/new.txt
      register: file_content

    - name: Print file content
      debug:
        var: file_content.stdout
