- name: Hello World Sample
  hosts: localhost
  tasks:
    - name: create file
      copy:
       content: "abc"
       dest: "/opt/work/sample2copy.txt"

    - name: view the content to see if the file exists
      command: ls /opt/work
      register: command_output
    - name: print to console
      debug:
        msg: "{{ command_output.stdout }}"
　　　- name:
      command: getenforce
      register: getenforce_output
    - name: print to console
      debug:
        msg: "{{ getenforce_output.stdout }}"
